version: '3'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.1/24
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ".env"
    command: mongod --replSet rs0 --bind_ip_all